name: schedule
on:
  schedule:
    - cron:  '0 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: post netlify build hook
      run: curl -X POST -d {} ${{ secrets.WEBHOOK_URL }}
